#!/bin/sh

# Xcode Cloud runs this script automatically right after cloning the repository,
# before it resolves the scheme and starts the build.
#
# NamazVakti.xcodeproj is generated by XcodeGen (from project.yml) and is gitignored,
# so a fresh clone has no .xcodeproj and no shared schemes for Xcode Cloud to build.
# Regenerate them here so the NamazVaktiiOS scheme exists before the build runs.

set -e

echo "==> Installing XcodeGen"
export HOMEBREW_NO_INSTALL_CLEANUP=1
if ! command -v xcodegen >/dev/null 2>&1; then
  brew install xcodegen
fi
xcodegen --version

echo "==> Generating NamazVakti.xcodeproj from project.yml"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "==> Done: $(ls -d *.xcodeproj 2>/dev/null)"
